# Generated by Django 5.0.6 on 2024-08-25 11:11

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=120, unique=True, validators=[main.models.file_name_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=120, unique=True, validators=[main.models.folder_name_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Css',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.file')),
                ('json', models.TextField(blank=True, default=None, null=True)),
                ('dict', models.TextField(blank=True, default=None, null=True)),
            ],
            bases=('main.file',),
        ),
        migrations.CreateModel(
            name='Html',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.file')),
                ('json', models.TextField(blank=True, default=None, null=True)),
                ('dict', models.TextField(blank=True, default=None, null=True)),
            ],
            bases=('main.file',),
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.folder'),
        ),
    ]
