# Generated by Django 5.0.6 on 2024-06-18 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Html',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('json', models.TextField(blank=True, default=None, null=True)),
                ('dict', models.TextField(blank=True, default=None, null=True)),
                ('str', models.TextField(blank=True, default=None, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.folder')),
            ],
        ),
    ]
