# Generated by Django 5.0.6 on 2024-08-20 07:18

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_html_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=120, unique=True, validators=[main.models.folder_name_validator]),
        ),
        migrations.CreateModel(
            name='Css',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('json', models.TextField(blank=True, default=None, null=True)),
                ('dict', models.TextField(blank=True, default=None, null=True)),
                ('str', models.TextField(blank=True, default=None, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.folder')),
            ],
        ),
    ]
