# Generated by Django 5.0.6 on 2024-08-20 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_folder_name_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='css',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.folder'),
        ),
        migrations.AlterField(
            model_name='html',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.folder'),
        ),
    ]
