# Generated by Django 5.0.6 on 2024-08-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_css_folder_alter_html_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='css',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.folder'),
        ),
        migrations.AlterField(
            model_name='html',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.folder'),
        ),
    ]
