# Generated by Django 5.0.6 on 2024-08-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_css_folder_alter_html_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='css',
            name='name',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='html',
            name='name',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
