# Generated by Django 5.0.6 on 2024-12-08 15:11

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='css',
            name='name',
            field=models.SlugField(max_length=120, unique=True, validators=[main.models.css_name_validator]),
        ),
        migrations.AlterField(
            model_name='html',
            name='json',
            field=models.TextField(blank=True, default=None, null=True, validators=[main.models.html_name_validator]),
        ),
    ]
